name: GDExtension
on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/README.md"
      - ".github/ISSUE_TEMPLATE/*"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/README.md"
      - ".github/ISSUE_TEMPLATE/*"
env:
  BASE_BRANCH: main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: linux-debug (x86_64)
            name: Linux (x86_64) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: linux-release (x86_64)
            name: Linux (x86_64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_64
          - identifier: linux-debug (x86_32)
            name: Linux (x86_32) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_32
          - identifier: linux-release (x86_32)
            name: Linux (x86_32) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_32

          - identifier: windows-debug (x86_64)
            name: Windows (x86_64) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release (x86_64)
            name: Windows (x86_64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: windows
            arch: x86_64
          - identifier: windows-debug (x86_32)
            name: Windows (x86_32) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: windows
            arch: x86_32
          - identifier: windows-release (x86_32)
            name: Windows (x86_32) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: windows
            arch: x86_32
          
          - identifier: android-release (x86_64)
            name: Android (x86_64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: android
            arch: x86_64
          - identifier: android-debug (x86_64)
            name: Android (x86_64) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: android
            arch: x86_64
          - identifier: android-release (arm64)
            name: Android (arm64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: android
            arch: arm64
          - identifier: android-debug (arm64)
            name: Android (arm64) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: android
            arch: arm64

          - identifier: macos-release (universal)
            name: MacOS (universal) - template_release
            runner: macos-latest
            target: template_release
            platform: macos
            arch: universal
          - identifier: macos-debug (universal)
            name: MacOS (universal) - template_debug
            runner: macos-latest
            target: template_debug
            platform: macos
            arch: universal
          
          - identifier: ios-release (arm64)
            name: IOS (arm64) - template_release
            runner: macos-latest
            target: template_release
            platform: ios
            arch: arm64
          - identifier: ios-debug (arm64)
            name: IOS (arm64) - template_debug
            runner: macos-latest
            target: template_debug
            platform: ios
            arch: arm64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install gcc-multilib
        if: ${{ startsWith(matrix.arch, 'x86_32') }}
        shell: sh
        run: |
          sudo apt install gcc-multilib g++-multilib
      - name: (Windows) Install mingw64
        if: ${{ startsWith(matrix.identifier, 'windows-') }}
        shell: sh
        run: |
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - name: (Android) Set up Java 11
        if: ${{ startsWith(matrix.identifier, 'android-') }}
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: (Android) Set up Android SDK
        if: ${{ startsWith(matrix.identifier, 'android-') }}
        uses: android-actions/setup-android@v2

      - name: (Android) Install Android Tools
        if: ${{ startsWith(matrix.identifier, 'android-') }}
        shell: sh
        run: |
          "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"
      - name: Set up Python
        uses: actions/setup-python@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version
      - name: Load .scons_cache directory
        id: godot-extension-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{env.BASE_BRANCH}}
      - name: Compile extension
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
          ls -l project/addons/luaAPI/bin/
      - name: Prepare artifact
        shell: sh
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          SCONS_CACHE_LIMIT: 7168
        run: |
          rm -rf ${{ github.workspace }}/project/.g* ${{ github.workspace }}/project/project.godot ${{ github.workspace }}/project/testing ${{ github.workspace }}/project/addons/luaAPI/bin/.gitignore
          cp -n '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' '${{ github.workspace }}/.github/LUA-LICENSE' ${{ github.workspace }}/project/addons/luaAPI
          cp '${{ github.workspace }}/external/luaJIT/COPYRIGHT' ${{ github.workspace }}/project/addons/luaAPI/LUAJIT-LICENSE
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/