name: ðŸ”— GHA
on:
  workflow_dispatch:

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/README.md"
      - "**/*.png"
      - "**/LICENSE"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/README.md"
      - "**/*.png"
      - "**/LICENSE"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"

env:
  GODOT_VERSION: 4.0.3

jobs:
  static-checks:
    name: ðŸ“Š Static checks
    uses: ./.github/workflows/static-checks.yml

  linux-build:
    name: ðŸ§ Linux
    needs: static-checks
    uses: ./.github/workflows/linux.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}

  macos-build:
    name: ðŸŽ macOS
    needs: static-checks
    uses: ./.github/workflows/macos-build.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}
  
  macos-package:
    name: ðŸŽ macOS Package
    needs: macos-build
    uses: ./.github/workflows/macos-package.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
  
  android-build:
    name: ðŸ¤– Android
    needs: static-checks
    uses: ./.github/workflows/android-build.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}
  
  android-package:
    name: ðŸ¤– Android Package
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: android-build
    uses: ./.github/workflows/android-package.yml
    
  ios-build:
    name: ðŸŽ IOS
    needs: static-checks
    uses: ./.github/workflows/ios-build.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}
  
  ios-package:
    name: ðŸŽ IOS Package
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: ios-build
    uses: ./.github/workflows/ios-package.yml
  
  web-build:
    name: ðŸŒ Web
    needs: static-checks
    uses: ./.github/workflows/web.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}

  windows-build:
    name: ðŸŽ¨ Windows
    needs: static-checks
    uses: ./.github/workflows/windows.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}
  
  gdextension-build:
    name: âš™ï¸ GDExtension
    needs: static-checks
    uses: ./.github/workflows/gdextension.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: ${{ env.GODOT_VERSION }}
  
  module-unit-tests:
    name: âš™ï¸ Module Unit Tests
    needs: linux-build
    uses: ./.github/workflows/module-unit-tests.yml
  
  gdextension-unit-tests:
    name: âš™ï¸ GDExtension Unit Tests
    needs: gdextension-build
    uses: ./.github/workflows/gdextension-unit-tests.yml
    with:
      godot_version: ${{ env.GODOT_VERSION }}

  template-version-file:
    name: ðŸ“ Create template version file
    needs: module-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Create version file
        run: |
          mkdir -p ${{ github.workspace }}/bin/templates
          echo ${{ env.GODOT_VERSION }}.stable > ${{ github.workspace }}/bin/templates/version.txt
      - name: Upload version file
        uses: actions/upload-artifact@v2
        with:
          name: export-templates
          path: ${{ github.workspace }}/bin/*